music/urls.py
from django.conf.urls import url
from django.conf.urls.i18n import urlpatterns
from . import views #. mean the current directory
app_name = 'music' #Adding name space to your project



urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),

    #music/album/add/
    url(r'album/add/$', views.AlbumCreate.as_view(), name='albumadd'),

    #music/album/2/
    url(r'album/(?P<pk>[0-9]+)/$', views.AlbumUpdate.as_view(), name = 'albumupdate'),

    #music/album/2/delete
    url(r'album/(?P<pk>[0-9]+)/delete/$', views.AlbumDelete.as_view(), name = 'albumdelete'),



    #music/ ^ indicates the starting of the regular expression
    #url(r'^$', views.index , name='index'), # '$' symbol indicates the end i.e. if there in nothing after $ '/' in url(here after music/ nothing is there)
    #/music/<album_id>/    #We pass this album_id detail in function
    #url(r'^(?P<album_id>[0-9]+)/$', views.detail, name='detail'), #^ represent beginning and $ represents end, album_id is the variable which can be used
    #name = 'detail' mean the above url pattern is recognized by detail
    #/music/<album_id>/favorite/
    #url(r'^(?P<album_id>[0-9]+)/favorite/$', views.favorite, name='favorite')#we no longer need this after creating generic views

]

website/urls.py
from django.conf.urls import include,url
from django.contrib import admin

urlpatterns = [
    url(r'^music/', include('music.urls')),  #Ehenver the project is run this is the first place the it looks for, from here it goes to music.urls
    url(r'^admin/', admin.site.urls),
]

music/models.py
from django.db import models
from django.core.urlresolvers import reverse

# Create your models here.

class Album(models.Model):
    artist = models.CharField(max_length=250)   #varialbe artist will be a column in database
    album_title = models.CharField(max_length=500) #CharField indicates what type of data is stored
    genre = models.CharField(max_length=100)
    album_logo = models.CharField(max_length=1000)

    def get_absolute_url(self):     #after filling in the form with above details where they need to be redircted is written here
        return reverse('music:detail', kwargs={'pk':self.pk}) #kwargs means key word args
    '''Whenever we take details view it take primary key of the album thats why
    we are using kwargs in order to pass pk to the details view'''

    def __str__(self): #String representaion of Album object in database shell in order to print the values of Album object
        return self.album_title + '-' + self.artist #Whenever you type Album.objects.all() you will get values in this format instead of Object Return

class Song(models.Model):       #Song needs to be part of album and we need to link it by ForeignKey
    album = models.ForeignKey(Album, on_delete=models.CASCADE)  #on_delete means when we delete Album any songs linked to album will also be deleted
    file_type = models.CharField(max_length=10)
    song_title = models.CharField(max_length=250)
    is_favorite = models.BooleanField(default=False)

    #Creating a String representation of Song
    def __str__(self):
        return self.song_title

music/views.py
#We are going to delete everything in views.py and start from scratch
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from .models import Album
#from django.http import Http404 #No longer needed after importing get_object_or_404
from django.http import HttpResponse
#from django.template import loader #to import template
#inorder to combine loader and render of template into one line do the below

class IndexView(generic.ListView):
    template_name = 'music/index.html'
    context_object_name = 'all_albums' #pass the result of queryset as all_albums

    def get_queryset(self):
        return Album.objects.all()  #by default the result is stored in object_list

class DetailView(generic.DetailView):
    model = Album
    template_name = 'music/detail.html'

class AlbumCreate(CreateView): #We dont need to specify the template name because of the naming convention album_form.html
    model = Album
    fields = ['artist', 'album_title', 'genre', 'album_logo']

class AlbumUpdate(UpdateView): #We dont need to specify the template name because of the naming convention album_form.html
    model = Album
    fields = ['artist', 'album_title', 'genre', 'album_logo']

class AlbumDelete(DeleteView):
    model = Album
    success_url = reverse_lazy('music:index')


'''from django.shortcuts import render, get_object_or_404
from .models import Album, Song'''
'''This index function contains the html code but we dont want this to be here.
we want to seperate html and python so we use template.
the below function is commented jut for reference and original function will be kept below that'''

'''def index(request):#This index function is mentioned in urls.py of music and name should ny same
    all_albums = Album.objects.all()# proper way to connect to the database
    #html = "<h1> This is list of Album</h1>"
    html = ''
    for albuma in all_albums:
        url = '/music/'+str(albuma.id)+'/'
        html += '<a href="'+url+'">'+albuma.album_title +'</a><br>'
    return HttpResponse(html)'''

'''def index(request): #This index function is mentioned in urls.py of music and name should ny same
    all_albums = Album.objects.all()# proper way to connect to the database
    #template = loader.get_template('music/index.html')
    #python by default looks into music/templates/ for template that why we dont give templates
    #Above template variable is reference to the index.html file
    #We are going to create a dictionary(i.e. context) inorder to pass all_albums information to the
    # template index.html and standard naming is context
    context = {
        'all_albums': all_albums,
    }
    #return HttpResponse(template.render(context, request)) We are passing context to index.html
    #instead of retruning HttpResponse we will return render in order to combile template loader and render
    return render(request, 'music/index.html', context)#HttpResponse is built inside render so internally its doing the same thing'''

#This whole Http404 can be generated by a small code given below
'''def detail(request , album_id):
    try:
        albums = Album.objects.get(pk=album_id)
    except Album.DoesNotExist:
        raise Http404("Album does not exists")
    return render(request, 'music/detail.html', {'albuma':albums})'''#What is in quotes is the variable sent to detail.html

'''def detail(request, album_id): #as there is a variable in url we are passing that in function detail
    album = get_object_or_404(Album, pk=album_id)
    return render(request, 'music/detail.html', {'albuma' : album})'''


    #return HttpResponse("<h2>This is new details admin id:" + str(album_id) +"</h2>")
    # This will excute no matter what id is there so to give output only for valid id we do the above

'''def favorite(request, album_id):
    album = get_object_or_404(Album, pk=album_id)
    try:
        selected_song = album.song_set.get(pk=request.POST['song'])
    except (KeyError, Song.DoesNotExists):
        return render(request, 'music/detail.html', {
            'albuma':album,
            'error_message':'You did not select a valid song' #This error_message is defined in detail.html
        })
    else:
        selected_song.is_favorite = True
        selected_song.save()
        return render(request, 'music/detail.html',{
            'albuma':album
        })'''

music/templates/music/album_form.html
<!--Note that the naming convention of this is name of the model in lower case(i.e. album) underscore form
    thats why name is album_form.html-->
{% extends 'music/base.html'%}
{% block title %}Add new Album{% endblock %}
{% block albums_active%}active{% endblock %}

{% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                        {%csrf_token%}
                        {% include 'music/form-template.html'%}
                        <div class="form-group">
                            <div class="col-sm-offset2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>

                    </form>

                </div>
            </div>
        </div>
    </div>

</div>
{% endblock %}

music/templates/music/base.html
<!-- This is going to be the generic blueprint of the html styling-->

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title%}Viberr{% endblock %}</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"/>
    <link href="https://fonts.googleapis.com/css?family=Satisfy" rel="stylesheet" type="text/css">  <!-- This is just for font-->
    <link rel="stylesheet" type="text/css" href="{% static 'music/style.css'%}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
</head>
<body>
    <nav class="navbar navbar-inverse"> <!-- Changes the color theme to dark color-->
    <div class="container-fluid">
        <!--Header-->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle = "collapse" data-target = "#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'music:index' %}">Viberr</a>
        </div>

        <!--Items-->
        <div class="collapse navbar-collapse" id="topNavBar">   <!-- Id top nav bar indicates that these all need to be collapsed. this id is from top-->
            <ul class="nav navbar-nav">
                <li class="active">
                    <a href="{% url 'music:index' %}">
                        <span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp; Albums
                    </a>
                </li>
                <li class="">
                    <a href="#">
                        <span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp; Songs
                    </a>
                </li>
            </ul>

            <form class="navbar-form navbar-left" role="search" method="get" action="#">
                <div class="form-group">
                    <input type="text" class="form-control" name="query" value="">
                </div>
                <button type="submit" class="btn btn-default">Search</button>
            </form>

            <ul class="nav navbar-nav navbar-right">
                <li class="">
                    <a href="{% url 'music:albumadd' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Album
                    </a>
                </li>
                <li class="">
                    <a href="#">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                    </a>
                </li>
            </ul>

        </div>
    </div>
</nav>

<!-- Now we also want to include the piece of code in index.html here so for that we declare a variable in block-->
{% block body%} <!-- You can name this variable anythin-->
{% endblock %}
</body>
</html>

music/templates/music/detail.html
{% extends 'music/base.html' %}
<!--{{ album }} Dessigning the page in better way-->
{% block title%}Album Details{% endblock %}
{% block body %}
    <img src="{{album.album_logo}}">

    <h1>{{ album.album_title }}</h1>
    <h3>{{ album.artist }}</h3>


    {% for song in album.song_set.all %}
        {{ song.song_title }}
        {% if song.is_favorite %}
            <img src="http://i.imgur.com/b9b13Rd.png"/>
        {% endif %}
        <br>
    {% endfor %}
    <input type="submit" value="Favorite">
{% endblock %}

<!--This was the code written earlier-->
<!-- Removing the below code because we are including forms
    <!--<ul>
        {% for song in albuma.song_set.all %}
        <li>{{ song.song_title }} - {{ song.file_type}}</li>
        {% endfor %}
    </ul>-->
    <!--We are cleaning this code for the generic view-->
    <!--{% if error_message %}
        <p><strong>{{ error_message }}</strong></p>
    {%endif%}-->

   <!--<form action="{% url 'music:favorite' albuma.id %}" method="post">-->
        <!--{% csrf_token %}
        {% for song in albuma.song_set.all%}
        <input type="radio" id="song{{forloop.counter}}" name="song" value="{{ song.id }}"/>-->
       <!-- <label for="song{{forloop.counter}}">
            {{song.song_title}}
            {% if song.is_favorite %}
                <img src="http://i.imgur.com/b9b13Rd.png">
            {%endif%}
        </label><br>
        {% endfor%}
        <input type="submit" value="Favorite">#on clicking submit it will go to the url of favorite
    </form>-->

music/templates/music/form-template.html
{% for field in form %}  <!-- As we are crating a form for Albums table all the values come in the variable form by default thats why written like this-->
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{field.err}}</span> <!-- in order to get error msg right on top of the field-->

        </div>
        <label class="control-label col-sm-2">{{ field.label_tag }}</label><!-- This thing is always gonna disply. Give artist ,album title etc-->
        <div class="col-sm-10">{{field}}</div>
    </div>
{% endfor %}

music/templates/music/index.html
{% extends 'music/base.html' %} <!-- This should be the 1st line of each file if we extend any html file-->
{% block albums_active %}active{% endblock %}
<!--We are commenting the all of this because we are creating a base file in which all of the styling of html is done-->
<!-- load the path to your static files-->
<!--{% load staticfiles %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"/>
<link href="https://fonts.googleapis.com/css?family=Satisfy" rel="stylesheet" type="text/css">
<link rel="stylesheet" type="text/css" href="{% static 'music/style.css'%}"/>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>-->

<!--<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <!--Header-->-->
        <!--<div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle = "collapse" data-target = "#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'music:index' %}">Viberr</a>
        </div>-->

        <!--Items-->
       <!-- <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="active">
                    <a href="{% url 'music:index' %}">
                        <span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp; Albums
                    </a>
                </li>
                <li class="">
                    <a href="#">
                        <span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp; Songs
                    </a>
                </li>
            </ul>

            <form class="navbar-form navbar-left" role="search" method="get" action="#">
                <div class="form-group">
                    <input type="text" class="form-control" name="query" value="">
                </div>
                <button type="submit" class="btn btn-default">Search</button>
            </form>

            <ul class="nav navbar-nav navbar-right">
                <li class="">
                    <a href="#">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Album
                    </a>
                </li>
                <li class="">
                    <a href="#">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                    </a>
                </li>
            </ul>

        </div>
    </div>
</nav>-->



    <!--{% if all_albums %}
        <h3>Here are all my Albums:</h3>
        <ul>-->
            <!--{% for albums in all_albums %}--><!-- When you use python code in html use this symbol-->
            <!--<li><a href="/music/{{ albums.id }}/">{{ albums.album_title }}</a> </li>We will remove hard coded url-->
              <!-- <li><a href="{% url 'music:detail' albums.id %}">{{ albums.album_title }}</a> </li>
            {% endfor %}
        </ul>
    {% else %}
        <h3>You dont have any albums</h3>
    {% endif %}-->
{% block body %}
    <div class="albums-container container-fluid">
        <div class="row">
            {% for albums in all_albums %}
                <div class="col-sm-4 col-lg-2">
                    <div class="thumbnail">
                        <!--Album logo-->
                        <a href="{% url 'music:detail' albums.id %}">
                            <img src="{{albums.album_logo}}" class="img-responsive">
                        </a>
                        <div class="caption">
                            <h2>{{all_albums.album_title}}</h2>
                            <h4>{{all_albums.artist}}</h4>

                            <a href="{% url 'music:detail' albums.id %}" class="btn btn-primary btn-sm">View Details</a>

                            <!--Delete-->
                            <form action="{% url 'music:albumdelete' albums.id %}" method="post" style="display: inline;">
                                {%csrf_token%}
                                <input type="hidden" name="album_id" value="{{albums.id}}"/>
                                <button type="submit" class="btn btn-default btn-sm">
                                    <span class="glyphicon glyphicon-trash"></span>
                                </button>
                            </form>

                            <!--Favorite-->
                            <a href="#" class="btn btn-default btn-sm">
                                <span class="glyphicon glyphicon-star {% if album.is_favorite %}active{% endif %}"></span>
                             </a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}